[phases.setup]
nixPkgs = ["python311", "ffmpeg", "gcc"]

[phases.install]
cmds = ["pip install poetry", "poetry config virtualenvs.create false", "poetry install --no-dev"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
